unique_ids:
  assets:
    ChatGPT Image Mar 16, 2026, 03_58_33 PM.png: '1774512482236198873406875.30063'
    standard-page.html: NOCVFHAYVEH2ASVMW6FZ7RPG3LHEZOT4
    theme.css: SEBQHBQDX3RSHX4DT23B6DQYP6MOF3T6
  forms:
    Form1: NBYQLXUJLBY7B5VHUM4VIU3XWJMACDOX
  modules: {}
  scripts: {}
  server_modules: {}
